---

- name: Add repository
  apt_repository:
    repo: "ppa:chris-lea/redis-server"

- name: Install
  apt:
    name: redis-server
    state: latest

- name: Supervise
  become: true
  lineinfile:
    dest: /etc/redis/redis.conf
    regexp: "supervised no"
    line: "supervised systemd"
  notify: restart redis
