---

- name: start php-fpm
  service:
    name: php{{ php.version }}-fpm
    state: started

- name: reload php-fpm
  service:
    name: php{{ php.version }}-fpm
    state: reloaded

- name: restart php-fpm
  service:
    name: php{{ php.version }}-fpm
    state: restarted
